import "./globals.css";
import MainLayout from "@/components/MainLayout";
import { ModalProvider } from "@/context/ModalContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Digital Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="no-scrollbar">
      <body className={`antialiased no-scrollbar`}>
        <Toaster />
        <ModalProvider>
          <MainLayout>{children}</MainLayout>
        </ModalProvider>
      </body>
    </html>
  );
}
